version: '3'

services:

  postgres:
    build: ./compose/postgres
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
      - ./data/postgres/backups:/app/data
    env_file: .env

  redis:
    build: ./compose/redis
    env_file: .env
    ports:
      - "0.0.0.0:6379:6379"

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: /app.bin/sync.sh && /app/bin/django.sh
    depends_on:
      - postgres
      - redis
    env_file: .env
    ports:
      - "0.0.0.0:5000:5000"
    volumes:
      - ./data/private:/app/private
      - ./data/public:/app/public

  nginx:
    build: ./compose/nginx
    depends_on:
      - django
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./data/public:/app/public
      - ./data/nginx/ssl:/etc/nginx/ssl
